import { State } from '../types/stateAreas';

export const STATES: State[] = [
  {
    id: 'abia',
    code: 'AB',
    name: 'Abia State',
    areas: [
      { id: 'aba-north', name: 'Aba North', stateId: 'abia' },
      { id: 'arochukwu', name: 'Arochukwu', stateId: 'abia' },
      { id: 'aba-south', name: 'Aba South', stateId: 'abia' },
      { id: 'bende', name: 'Bende', stateId: 'abia' },
      { id: 'ikwuano', name: 'Ikwuano', stateId: 'abia' },
      { id: 'isiala-ngwa-north', name: 'Isiala-Ngwa North', stateId: 'abia' },
      { id: 'isiala-ngwa-south', name: 'Isiala-Ngwa South', stateId: 'abia' },
      { id: 'isuikwato', name: 'Isuikwato', stateId: 'abia' },
      { id: 'obi-ngwa', name: 'Obi Ngwa', stateId: 'abia' },
      { id: 'ohafia', name: 'Ohafia', stateId: 'abia' },
      { id: 'osisioma-ngwa', name: 'Osisioma Ngwa', stateId: 'abia' },
      { id: 'ukwa-east', name: 'Ukwa East', stateId: 'abia' },
      { id: 'ugwunagbo', name: 'Ugwunagbo', stateId: 'abia' },
      { id: 'umu-nneochi', name: 'Umu-Nneochi', stateId: 'abia' },
      { id: 'umuahia-north', name: 'Umuahia North', stateId: 'abia' },
      { id: 'umuahia-south', name: 'Umuahia South', stateId: 'abia' },
      { id: 'ukwa-west', name: 'Ukwa West', stateId: 'abia' },
    ],
  },
  {
    id: 'adamawa',
    code: 'AD',
    name: 'Adamawa State',
    areas: [
      { id: 'demsa', name: 'Demsa', stateId: 'adamawa' },
      { id: 'fufore', name: 'Fufore', stateId: 'adamawa' },
      { id: 'ganye', name: 'Ganye', stateId: 'adamawa' },
      { id: 'girie', name: 'Girie', stateId: 'adamawa' },
      { id: 'gombi', name: 'Gombi', stateId: 'adamawa' },
      { id: 'guyuk', name: 'Guyuk', stateId: 'adamawa' },
      { id: 'hong', name: 'Hong', stateId: 'adamawa' },
      { id: 'jada', name: 'Jada', stateId: 'adamawa' },
      { id: 'lamurde', name: 'Lamurde', stateId: 'adamawa' },
      { id: 'mayo-belwa', name: 'Mayo-Belwa', stateId: 'adamawa' },
      { id: 'madagali', name: 'Madagali', stateId: 'adamawa' },
      { id: 'maiha', name: 'Maiha', stateId: 'adamawa' },
      { id: 'michika', name: 'Michika', stateId: 'adamawa' },
      { id: 'mubi-north', name: 'Mubi North', stateId: 'adamawa' },
      { id: 'mubi-south', name: 'Mubi South', stateId: 'adamawa' },
      { id: 'numan', name: 'Numan', stateId: 'adamawa' },
      { id: 'shelleng', name: 'Shelleng', stateId: 'adamawa' },
      { id: 'song', name: 'Song', stateId: 'adamawa' },
      { id: 'toungo', name: 'Toungo', stateId: 'adamawa' },
      { id: 'yola-north', name: 'Yola North', stateId: 'adamawa' },
      { id: 'yola-south', name: 'Yola South', stateId: 'adamawa' },
    ],
  },
  {
    id: 'akwa-ibom',
    code: 'AK',
    name: 'Akwa Ibom State',
    areas: [
      { id: 'abak', name: 'Abak', stateId: 'akwa-ibom' },
      { id: 'eket', name: 'Eket', stateId: 'akwa-ibom' },
      { id: 'eastern-obolo', name: 'Eastern Obolo', stateId: 'akwa-ibom' },
      { id: 'etim-ekpo', name: 'Etim Ekpo', stateId: 'akwa-ibom' },
      { id: 'esit-eket', name: 'Esit Eket', stateId: 'akwa-ibom' },
      { id: 'etinan', name: 'Etinan', stateId: 'akwa-ibom' },
      { id: 'essien-udim', name: 'Essien Udim', stateId: 'akwa-ibom' },
      { id: 'ikot-abasi', name: 'Ikot Abasi', stateId: 'akwa-ibom' },
      { id: 'ibeno', name: 'Ibeno', stateId: 'akwa-ibom' },
      { id: 'ikot-ekpene', name: 'Ikot Ekpene', stateId: 'akwa-ibom' },
      { id: 'ibiono-ibom', name: 'Ibiono Ibom', stateId: 'akwa-ibom' },
      { id: 'ika', name: 'Ika', stateId: 'akwa-ibom' },
      { id: 'ini', name: 'Ini', stateId: 'akwa-ibom' },
      { id: 'ikono', name: 'Ikono', stateId: 'akwa-ibom' },
      { id: 'ibesikpo-asutan', name: 'Ibesikpo Asutan', stateId: 'akwa-ibom' },
      { id: 'itu', name: 'Itu', stateId: 'akwa-ibom' },
      { id: 'mbo', name: 'Mbo', stateId: 'akwa-ibom' },
      { id: 'mkpat-enin', name: 'Mkpat Enin', stateId: 'akwa-ibom' },
      { id: 'nsit-atai', name: 'Nsit Atai', stateId: 'akwa-ibom' },
      { id: 'nsit-ibom', name: 'Nsit Ibom', stateId: 'akwa-ibom' },
      { id: 'nsit-ubium', name: 'Nsit Ubium', stateId: 'akwa-ibom' },
      { id: 'oruk-anam', name: 'Oruk Anam', stateId: 'akwa-ibom' },
      { id: 'obot-akara', name: 'Obot Akara', stateId: 'akwa-ibom' },
      { id: 'okobo', name: 'Okobo', stateId: 'akwa-ibom' },
      { id: 'onna', name: 'Onna', stateId: 'akwa-ibom' },
      { id: 'oron', name: 'Oron', stateId: 'akwa-ibom' },
      { id: 'ukanafun', name: 'Ukanafun', stateId: 'akwa-ibom' },
      { id: 'urue-offong-oruko', name: 'Urue-Offong/Oruko', stateId: 'akwa-ibom' },
      { id: 'uruan', name: 'Uruan', stateId: 'akwa-ibom' },
      { id: 'udung-uko', name: 'Udung Uko', stateId: 'akwa-ibom' },
      { id: 'uyo', name: 'Uyo', stateId: 'akwa-ibom' },
    ],
  },
  {
    id: 'anambra',
    code: 'AN',
    name: 'Anambra State',
    areas: [
      { id: 'anaocha', name: 'Anaocha', stateId: 'anambra' },
      { id: 'anambra-east', name: 'Anambra East', stateId: 'anambra' },
      { id: 'aguata', name: 'Aguata', stateId: 'anambra' },
      { id: 'awka-north', name: 'Awka North', stateId: 'anambra' },
      { id: 'awka-south', name: 'Awka South', stateId: 'anambra' },
      { id: 'anambra-west', name: 'Anambra West', stateId: 'anambra' },
      { id: 'ayamelum', name: 'Ayamelum', stateId: 'anambra' },
      { id: 'dunukofia', name: 'Dunukofia', stateId: 'anambra' },
      { id: 'ekwusigo', name: 'Ekwusigo', stateId: 'anambra' },
      { id: 'ihiala', name: 'Ihiala', stateId: 'anambra' },
      { id: 'idemili-north', name: 'Idemili North', stateId: 'anambra' },
      { id: 'idemili-south', name: 'Idemili South', stateId: 'anambra' },
      { id: 'njikoka', name: 'Njikoka', stateId: 'anambra' },
      { id: 'nnewi-north', name: 'Nnewi North', stateId: 'anambra' },
      { id: 'nnewi-south', name: 'Nnewi South', stateId: 'anambra' },
      { id: 'orumba-south', name: 'Orumba South', stateId: 'anambra' },
      { id: 'ogbaru', name: 'Ogbaru', stateId: 'anambra' },
      { id: 'onitsha-north', name: 'Onitsha North', stateId: 'anambra' },
      { id: 'orumba-north', name: 'Orumba North', stateId: 'anambra' },
      { id: 'onitsha-south', name: 'Onitsha South', stateId: 'anambra' },
      { id: 'oyi', name: 'Oyi', stateId: 'anambra' },
    ],
  },
  {
    id: 'bauchi',
    code: 'BA',
    name: 'Bauchi State',
    areas: [
      { id: 'alkaleri', name: 'Alkaleri', stateId: 'bauchi' },
      { id: 'bauchi', name: 'Bauchi', stateId: 'bauchi' },
      { id: 'bogoro', name: 'Bogoro', stateId: 'bauchi' },
      { id: 'damban', name: 'Damban', stateId: 'bauchi' },
      { id: 'dass', name: 'Dass', stateId: 'bauchi' },
      { id: 'darazo', name: 'Darazo', stateId: 'bauchi' },
      { id: 'giade', name: 'Giade', stateId: 'bauchi' },
      { id: 'gamawa', name: 'Gamawa', stateId: 'bauchi' },
      { id: 'ganjuwa', name: 'Ganjuwa', stateId: 'bauchi' },
      { id: 'itas-gadau', name: 'Itas/Gadau', stateId: 'bauchi' },
      { id: 'jamaare', name: 'Jama\'are', stateId: 'bauchi' },
      { id: 'katagum', name: 'Katagum', stateId: 'bauchi' },
      { id: 'kirfi', name: 'Kirfi', stateId: 'bauchi' },
      { id: 'misau', name: 'Misau', stateId: 'bauchi' },
      { id: 'ningi', name: 'Ningi', stateId: 'bauchi' },
      { id: 'shira', name: 'Shira', stateId: 'bauchi' },
      { id: 'tafawa-balewa', name: 'Tafawa-Balewa', stateId: 'bauchi' },
      { id: 'toro', name: 'Toro', stateId: 'bauchi' },
      { id: 'warji', name: 'Warji', stateId: 'bauchi' },
      { id: 'zaki', name: 'Zaki', stateId: 'bauchi' },
    ],
  },
  {
    id: 'benue',
    code: 'BE',
    name: 'Benue State',
    areas: [
      { id: 'apa', name: 'Apa', stateId: 'benue' },
      { id: 'agatu', name: 'Agatu', stateId: 'benue' },
      { id: 'ado', name: 'Ado', stateId: 'benue' },
      { id: 'buruku', name: 'Buruku', stateId: 'benue' },
      { id: 'gboko', name: 'Gboko', stateId: 'benue' },
      { id: 'gwer-east', name: 'Gwer East', stateId: 'benue' },
      { id: 'guma', name: 'Guma', stateId: 'benue' },
      { id: 'gwer-west', name: 'Gwer West', stateId: 'benue' },
      { id: 'katsina-ala', name: 'Katsina-Ala', stateId: 'benue' },
      { id: 'konshisha', name: 'Konshisha', stateId: 'benue' },
      { id: 'kwande', name: 'Kwande', stateId: 'benue' },
      { id: 'logo', name: 'Logo', stateId: 'benue' },
      { id: 'makurdi', name: 'Makurdi', stateId: 'benue' },
      { id: 'obi', name: 'Obi', stateId: 'benue' },
      { id: 'ogbadibo', name: 'Ogbadibo', stateId: 'benue' },
      { id: 'ohimini', name: 'Ohimini', stateId: 'benue' },
      { id: 'oju', name: 'Oju', stateId: 'benue' },
      { id: 'okpokwu', name: 'Okpokwu', stateId: 'benue' },
      { id: 'oturkpo', name: 'Oturkpo', stateId: 'benue' },
      { id: 'tarka', name: 'Tarka', stateId: 'benue' },
      { id: 'ukum', name: 'Ukum', stateId: 'benue' },
      { id: 'ushongo', name: 'Ushongo', stateId: 'benue' },
      { id: 'vandeikya', name: 'Vandeikya', stateId: 'benue' },
    ],
  },
  {
    id: 'borno',
    code: 'BO',
    name: 'Borno State',
    areas: [
      { id: 'abadam', name: 'Abadam', stateId: 'borno' },
      { id: 'askira-uba', name: 'Askira/Uba', stateId: 'borno' },
      { id: 'biu', name: 'Biu', stateId: 'borno' },
      { id: 'bama', name: 'Bama', stateId: 'borno' },
      { id: 'bayo', name: 'Bayo', stateId: 'borno' },
      { id: 'chibok', name: 'Chibok', stateId: 'borno' },
      { id: 'damboa', name: 'Damboa', stateId: 'borno' },
      { id: 'dikwa', name: 'Dikwa', stateId: 'borno' },
      { id: 'gubio', name: 'Gubio', stateId: 'borno' },
      { id: 'guzamala', name: 'Guzamala', stateId: 'borno' },
      { id: 'gwoza', name: 'Gwoza', stateId: 'borno' },
      { id: 'hawul', name: 'Hawul', stateId: 'borno' },
      { id: 'jere', name: 'Jere', stateId: 'borno' },
      { id: 'kaga', name: 'Kaga', stateId: 'borno' },
      { id: 'kala-balge', name: 'Kala/Balge', stateId: 'borno' },
      { id: 'kwaya-kusar', name: 'Kwaya Kusar', stateId: 'borno' },
      { id: 'konduga', name: 'Konduga', stateId: 'borno' },
      { id: 'kukawa', name: 'Kukawa', stateId: 'borno' },
      { id: 'mobbar', name: 'Mobbar', stateId: 'borno' },
      { id: 'maiduguri', name: 'Maiduguri', stateId: 'borno' },
      { id: 'mafa', name: 'Mafa', stateId: 'borno' },
      { id: 'magumeri', name: 'Magumeri', stateId: 'borno' },
      { id: 'monguno', name: 'Monguno', stateId: 'borno' },
      { id: 'marte', name: 'Marte', stateId: 'borno' },
      { id: 'ngala', name: 'Ngala', stateId: 'borno' },
      { id: 'nganzai', name: 'Nganzai', stateId: 'borno' },
      { id: 'shani', name: 'Shani', stateId: 'borno' },
    ],
  },
  {
    id: 'bayelsa',
    code: 'BY',
    name: 'Bayelsa State',
    areas: [
      { id: 'brass', name: 'Brass', stateId: 'bayelsa' },
      { id: 'ekeremor', name: 'Ekeremor', stateId: 'bayelsa' },
      { id: 'kolokuma-opokuma', name: 'Kolokuma/Opokuma', stateId: 'bayelsa' },
      { id: 'nembe', name: 'Nembe', stateId: 'bayelsa' },
      { id: 'ogbia', name: 'Ogbia', stateId: 'bayelsa' },
      { id: 'sagbama', name: 'Sagbama', stateId: 'bayelsa' },
      { id: 'southern-ijaw', name: 'Southern Ijaw', stateId: 'bayelsa' },
      { id: 'yenegoa', name: 'Yenegoa', stateId: 'bayelsa' },
    ],
  },
  {
    id: 'cross-river',
    code: 'CR',
    name: 'Cross River State',
    areas: [
      { id: 'abi', name: 'Abi', stateId: 'cross-river' },
      { id: 'akamkpa', name: 'Akamkpa', stateId: 'cross-river' },
      { id: 'akpabuyo', name: 'Akpabuyo', stateId: 'cross-river' },
      { id: 'bakassi', name: 'Bakassi', stateId: 'cross-river' },
      { id: 'bekwarra', name: 'Bekwarra', stateId: 'cross-river' },
      { id: 'biase', name: 'Biase', stateId: 'cross-river' },
      { id: 'boki', name: 'Boki', stateId: 'cross-river' },
      { id: 'calabar-municipal', name: 'Calabar-Municipal', stateId: 'cross-river' },
      { id: 'calabar-south', name: 'Calabar South', stateId: 'cross-river' },
      { id: 'etung', name: 'Etung', stateId: 'cross-river' },
      { id: 'ikom', name: 'Ikom', stateId: 'cross-river' },
      { id: 'obubra', name: 'Obubra', stateId: 'cross-river' },
      { id: 'ogoja', name: 'Ogoja', stateId: 'cross-river' },
      { id: 'obanliku', name: 'Obanliku', stateId: 'cross-river' },
      { id: 'odukpani', name: 'Odukpani', stateId: 'cross-river' },
      { id: 'obudu', name: 'Obudu', stateId: 'cross-river' },
      { id: 'yakurr', name: 'Yakurr', stateId: 'cross-river' },
      { id: 'yala', name: 'Yala', stateId: 'cross-river' },
    ],
  },
  {
    id: 'delta',
    code: 'DE',
    name: 'Delta State',
    areas: [
      { id: 'aniocha-north', name: 'Aniocha North', stateId: 'delta' },
      { id: 'aniocha-south', name: 'Aniocha South', stateId: 'delta' },
      { id: 'bomadi', name: 'Bomadi', stateId: 'delta' },
      { id: 'burutu', name: 'Burutu', stateId: 'delta' },
      { id: 'ethiope-east', name: 'Ethiope East', stateId: 'delta' },
      { id: 'ethiope-west', name: 'Ethiope West', stateId: 'delta' },
      { id: 'ika-north-east', name: 'Ika North East', stateId: 'delta' },
      { id: 'ika-south', name: 'Ika South', stateId: 'delta' },
      { id: 'isoko-north', name: 'Isoko North', stateId: 'delta' },
      { id: 'isoko-south', name: 'Isoko South', stateId: 'delta' },
      { id: 'ndokwa-east', name: 'Ndokwa East', stateId: 'delta' },
      { id: 'ndokwa-west', name: 'Ndokwa West', stateId: 'delta' },
      { id: 'okpe', name: 'Okpe', stateId: 'delta' },
      { id: 'oshimili-north', name: 'Oshimili North', stateId: 'delta' },
      { id: 'oshimili-south', name: 'Oshimili South', stateId: 'delta' },
      { id: 'patani', name: 'Patani', stateId: 'delta' },
      { id: 'sapele', name: 'Sapele', stateId: 'delta' },
      { id: 'udu', name: 'Udu', stateId: 'delta' },
      { id: 'ukwuani', name: 'Ukwuani', stateId: 'delta' },
      { id: 'ughelli-north', name: 'Ughelli North', stateId: 'delta' },
      { id: 'ughelli-south', name: 'Ughelli South', stateId: 'delta' },
      { id: 'uvwie', name: 'Uvwie', stateId: 'delta' },
      { id: 'warri-north', name: 'Warri North', stateId: 'delta' },
      { id: 'warri-south', name: 'Warri South', stateId: 'delta' },
      { id: 'warri-south-west', name: 'Warri South West', stateId: 'delta' },
    ],
  },
  {
    id: 'ebonyi',
    code: 'EB',
    name: 'Ebonyi State',
    areas: [
      { id: 'abakaliki', name: 'Abakaliki', stateId: 'ebonyi' },
      { id: 'afikpo-north', name: 'Afikpo North', stateId: 'ebonyi' },
      { id: 'afikpo-south', name: 'Afikpo South', stateId: 'ebonyi' },
      { id: 'ebonyi', name: 'Ebonyi', stateId: 'ebonyi' },
      { id: 'ezza-north', name: 'Ezza North', stateId: 'ebonyi' },
      { id: 'ezza-south', name: 'Ezza South', stateId: 'ebonyi' },
      { id: 'ikwo', name: 'Ikwo', stateId: 'ebonyi' },
      { id: 'ishielu', name: 'Ishielu', stateId: 'ebonyi' },
      { id: 'ivo', name: 'Ivo', stateId: 'ebonyi' },
      { id: 'izzi', name: 'Izzi', stateId: 'ebonyi' },
      { id: 'ohaukwu', name: 'Ohaukwu', stateId: 'ebonyi' },
      { id: 'onicha', name: 'Onicha', stateId: 'ebonyi' },
      { id: 'ohaozara', name: 'Ohaozara', stateId: 'ebonyi' },
    ],
  },
  {
    id: 'edo',
    code: 'ED',
    name: 'Edo State',
    areas: [
      { id: 'akoko-edo', name: 'Akoko-Edo', stateId: 'edo' },
      { id: 'esan-central', name: 'Esan Central', stateId: 'edo' },
      { id: 'egor', name: 'Egor', stateId: 'edo' },
      { id: 'etsako-east', name: 'Etsako East', stateId: 'edo' },
      { id: 'esan-north-east', name: 'Esan North East', stateId: 'edo' },
      { id: 'etsako-west', name: 'Etsako West', stateId: 'edo' },
      { id: 'esan-south-east', name: 'Esan South East', stateId: 'edo' },
      { id: 'etsako-central', name: 'Etsako Central', stateId: 'edo' },
      { id: 'esan-west', name: 'Esan West', stateId: 'edo' },
      { id: 'igueben', name: 'Igueben', stateId: 'edo' },
      { id: 'ikpoba-okha', name: 'Ikpoba-Okha', stateId: 'edo' },
      { id: 'owan-east', name: 'Owan East', stateId: 'edo' },
      { id: 'orhionmwon', name: 'Orhionmwon', stateId: 'edo' },
      { id: 'ovia-north-east', name: 'Ovia North East', stateId: 'edo' },
      { id: 'oredo', name: 'Oredo', stateId: 'edo' },
      { id: 'ovia-south-west', name: 'Ovia South West', stateId: 'edo' },
      { id: 'owan-west', name: 'Owan West', stateId: 'edo' },
      { id: 'uhunmwonde', name: 'Uhunmwonde', stateId: 'edo' },
    ],
  },
  {
    id: 'ekiti',
    code: 'EK',
    name: 'Ekiti State',
    areas: [
      { id: 'ado-ekiti', name: 'Ado Ekiti', stateId: 'ekiti' },
      { id: 'aiyekire', name: 'Aiyekire', stateId: 'ekiti' },
      { id: 'ekiti-east', name: 'Ekiti East', stateId: 'ekiti' },
      { id: 'efon', name: 'Efon', stateId: 'ekiti' },
      { id: 'emure', name: 'Emure', stateId: 'ekiti' },
      { id: 'ekiti-south-west', name: 'Ekiti South West', stateId: 'ekiti' },
      { id: 'ekiti-west', name: 'Ekiti West', stateId: 'ekiti' },
      { id: 'idosi-osi', name: 'Idosi-Osi', stateId: 'ekiti' },
      { id: 'irepodun-ifelodun', name: 'Irepodun/Ifelodun', stateId: 'ekiti' },
      { id: 'ijero', name: 'Ijero', stateId: 'ekiti' },
      { id: 'ikole', name: 'Ikole', stateId: 'ekiti' },
      { id: 'ilejemeje', name: 'Ilejemeje', stateId: 'ekiti' },
      { id: 'ise-orun', name: 'Ise/Orun', stateId: 'ekiti' },
      { id: 'ikere', name: 'Ikere', stateId: 'ekiti' },
      { id: 'moba', name: 'Moba', stateId: 'ekiti' },
      { id: 'oye', name: 'Oye', stateId: 'ekiti' },
    ],
  },
  {
    id: 'enugu',
    code: 'EN',
    name: 'Enugu State',
    areas: [
      { id: 'aninri', name: 'Aninri', stateId: 'enugu' },
      { id: 'awgu', name: 'Awgu', stateId: 'enugu' },
      { id: 'enugu-east', name: 'Enugu East', stateId: 'enugu' },
      { id: 'enugu-north', name: 'Enugu North', stateId: 'enugu' },
      { id: 'enugu-south', name: 'Enugu South', stateId: 'enugu' },
      { id: 'ezeagu', name: 'Ezeagu', stateId: 'enugu' },
      { id: 'igbo-etiti', name: 'Igbo-Etiti', stateId: 'enugu' },
      { id: 'igbo-eze-north', name: 'Igbo-Eze North', stateId: 'enugu' },
      { id: 'igbo-eze-south', name: 'Igbo-Eze South', stateId: 'enugu' },
      { id: 'isi-uzo', name: 'Isi-Uzo', stateId: 'enugu' },
      { id: 'nkanu-east', name: 'Nkanu East', stateId: 'enugu' },
      { id: 'nsukka', name: 'Nsukka', stateId: 'enugu' },
      { id: 'nkanu-west', name: 'Nkanu West', stateId: 'enugu' },
      { id: 'oji-river', name: 'Oji-River', stateId: 'enugu' },
      { id: 'udi', name: 'Udi', stateId: 'enugu' },
      { id: 'udenu', name: 'Udenu', stateId: 'enugu' },
      { id: 'uzo-uwani', name: 'Uzo-Uwani', stateId: 'enugu' },
    ],
  },
  {
    id: 'fct',
    code: 'FC',
    name: 'Federal Capital Territory',
    areas: [
      { id: 'abaji', name: 'Abaji', stateId: 'fct' },
      { id: 'amac', name: 'Abuja Municipal Area Council (AMAC)', stateId: 'fct' },
      { id: 'bwari', name: 'Bwari', stateId: 'fct' },
      { id: 'gwagwalada', name: 'Gwagwalada', stateId: 'fct' },
      { id: 'kuje', name: 'Kuje', stateId: 'fct' },
      { id: 'kwali', name: 'Kwali', stateId: 'fct' },
    ],
  },
  {
    id: 'gombe',
    code: 'GO',
    name: 'Gombe State',
    areas: [
      { id: 'akko', name: 'Akko', stateId: 'gombe' },
      { id: 'balanga', name: 'Balanga', stateId: 'gombe' },
      { id: 'billiri', name: 'Billiri', stateId: 'gombe' },
      { id: 'dukku', name: 'Dukku', stateId: 'gombe' },
      { id: 'funakaye', name: 'Funakaye', stateId: 'gombe' },
      { id: 'gombe', name: 'Gombe', stateId: 'gombe' },
      { id: 'kaltungo', name: 'Kaltungo', stateId: 'gombe' },
      { id: 'kwami', name: 'Kwami', stateId: 'gombe' },
      { id: 'nafada', name: 'Nafada', stateId: 'gombe' },
      { id: 'shomgom', name: 'Shomgom', stateId: 'gombe' },
      { id: 'yamaltu-deba', name: 'Yamaltu/Deba', stateId: 'gombe' },
    ],
  },
  {
    id: 'imo',
    code: 'IM',
    name: 'Imo State',
    areas: [
      { id: 'aboh-mbaise', name: 'Aboh-Mbaise', stateId: 'imo' },
      { id: 'ahiazu-mbaise', name: 'Ahiazu-Mbaise', stateId: 'imo' },
      { id: 'ehime-mbano', name: 'Ehime-Mbano', stateId: 'imo' },
      { id: 'ezinihitte', name: 'Ezinihitte', stateId: 'imo' },
      { id: 'ideato-south', name: 'Ideato South', stateId: 'imo' },
      { id: 'ikeduru', name: 'Ikeduru', stateId: 'imo' },
      { id: 'isiala-mbano', name: 'Isiala Mbano', stateId: 'imo' },
      { id: 'ideato-north', name: 'Ideato North', stateId: 'imo' },
      { id: 'isu', name: 'Isu', stateId: 'imo' },
      { id: 'ihitte-uboma', name: 'Ihitte/Uboma', stateId: 'imo' },
      { id: 'mbaitoli', name: 'Mbaitoli', stateId: 'imo' },
      { id: 'njaba', name: 'Njaba', stateId: 'imo' },
      { id: 'nkwerre', name: 'Nkwerre', stateId: 'imo' },
      { id: 'ngor-okpala', name: 'Ngor-Okpala', stateId: 'imo' },
      { id: 'nwangele', name: 'Nwangele', stateId: 'imo' },
      { id: 'obowo', name: 'Obowo', stateId: 'imo' },
      { id: 'oru-east', name: 'Oru East', stateId: 'imo' },
      { id: 'oguta', name: 'Oguta', stateId: 'imo' },
      { id: 'ohaji-egbema', name: 'Ohaji/Egbema', stateId: 'imo' },
      { id: 'okigwe', name: 'Okigwe', stateId: 'imo' },
      { id: 'orlu', name: 'Orlu', stateId: 'imo' },
      { id: 'owerri-municipal', name: 'Owerri-Municipal', stateId: 'imo' },
      { id: 'owerri-north', name: 'Owerri North', stateId: 'imo' },
      { id: 'orsu', name: 'Orsu', stateId: 'imo' },
      { id: 'oru-west', name: 'Oru West', stateId: 'imo' },
      { id: 'owerri-west', name: 'Owerri West', stateId: 'imo' },
      { id: 'unuimo', name: 'Unuimo', stateId: 'imo' },
    ],
  },
  {
    id: 'jigawa',
    code: 'JI',
    name: 'Jigawa State',
    areas: [
      { id: 'auyo', name: 'Auyo', stateId: 'jigawa' },
      { id: 'babura', name: 'Babura', stateId: 'jigawa' },
      { id: 'biriniwa', name: 'Biriniwa', stateId: 'jigawa' },
      { id: 'birnin-kudu', name: 'Birnin Kudu', stateId: 'jigawa' },
      { id: 'buji', name: 'Buji', stateId: 'jigawa' },
      { id: 'dutse', name: 'Dutse', stateId: 'jigawa' },
      { id: 'gagarawa', name: 'Gagarawa', stateId: 'jigawa' },
      { id: 'garki', name: 'Garki', stateId: 'jigawa' },
      { id: 'gumel', name: 'Gumel', stateId: 'jigawa' },
      { id: 'gwaram', name: 'Gwaram', stateId: 'jigawa' },
      { id: 'guri', name: 'Guri', stateId: 'jigawa' },
      { id: 'gwiwa', name: 'Gwiwa', stateId: 'jigawa' },
      { id: 'hadejia', name: 'Hadejia', stateId: 'jigawa' },
      { id: 'jahun', name: 'Jahun', stateId: 'jigawa' },
      { id: 'kaugama', name: 'Kaugama', stateId: 'jigawa' },
      { id: 'kafin-hausa', name: 'Kafin Hausa', stateId: 'jigawa' },
      { id: 'kiyawa', name: 'Kiyawa', stateId: 'jigawa' },
      { id: 'kiri-kasama', name: 'Kiri Kasama', stateId: 'jigawa' },
      { id: 'kazaure', name: 'Kazaure', stateId: 'jigawa' },
      { id: 'maigatari', name: 'Maigatari', stateId: 'jigawa' },
      { id: 'miga', name: 'Miga', stateId: 'jigawa' },
      { id: 'malumfashi', name: 'Malumfashi', stateId: 'jigawa' },
      { id: 'mani', name: 'Mani', stateId: 'jigawa' },
      { id: 'mashi', name: 'Mashi', stateId: 'jigawa' },
      { id: 'musawa', name: 'Musawa', stateId: 'jigawa' },
      { id: 'matazu', name: 'Matazu', stateId: 'jigawa' },
      { id: 'rimi', name: 'Rimi', stateId: 'jigawa' },
      { id: 'sabuwa', name: 'Sabuwa', stateId: 'jigawa' },
      { id: 'safana', name: 'Safana', stateId: 'jigawa' },
      { id: 'sandamu', name: 'Sandamu', stateId: 'jigawa' },
      { id: 'zango', name: 'Zango', stateId: 'jigawa' },
    ],
  },
  {
    id: 'kaduna',
    code: 'KD',
    name: 'Kaduna State',
    areas: [
      { id: 'birnin-gwari', name: 'Birnin-Gwari', stateId: 'kaduna' },
      { id: 'chikun', name: 'Chikun', stateId: 'kaduna' },
      { id: 'giwa', name: 'Giwa', stateId: 'kaduna' },
      { id: 'igabi', name: 'Igabi', stateId: 'kaduna' },
      { id: 'ikara', name: 'Ikara', stateId: 'kaduna' },
      { id: 'jaba', name: 'Jaba', stateId: 'kaduna' },
      { id: 'jemaa', name: 'Jemaa', stateId: 'kaduna' },
      { id: 'kaura', name: 'Kaura', stateId: 'kaduna' },
      { id: 'kubau', name: 'Kubau', stateId: 'kaduna' },
      { id: 'kachia', name: 'Kachia', stateId: 'kaduna' },
      { id: 'kagarko', name: 'Kagarko', stateId: 'kaduna' },
      { id: 'kajuru', name: 'Kajuru', stateId: 'kaduna' },
      { id: 'kaduna-north', name: 'Kaduna North', stateId: 'kaduna' },
      { id: 'kauru', name: 'Kauru', stateId: 'kaduna' },
      { id: 'kaduna-south', name: 'Kaduna South', stateId: 'kaduna' },
      { id: 'kudan', name: 'Kudan', stateId: 'kaduna' },
      { id: 'lere', name: 'Lere', stateId: 'kaduna' },
      { id: 'makarfi', name: 'Makarfi', stateId: 'kaduna' },
      { id: 'sanga', name: 'Sanga', stateId: 'kaduna' },
      { id: 'sabon-gari', name: 'Sabon-Gari', stateId: 'kaduna' },
      { id: 'soba', name: 'Soba', stateId: 'kaduna' },
      { id: 'zarki', name: 'Zarki', stateId: 'kaduna' },
      { id: 'zangon-kataf', name: 'Zangon-Kataf', stateId: 'kaduna' },
    ],
  },
  {
    id: 'kebbi',
    code: 'KE',
    name: 'Kebbi State',
    areas: [
      { id: 'arewa-dandi', name: 'Arewa-Dandi', stateId: 'kebbi' },
      { id: 'aleiro', name: 'Aleiro', stateId: 'kebbi' },
      { id: 'argungu', name: 'Argungu', stateId: 'kebbi' },
      { id: 'augie', name: 'Augie', stateId: 'kebbi' },
      { id: 'bagudo', name: 'Bagudo', stateId: 'kebbi' },
      { id: 'birnin-kebbi', name: 'Birnin Kebbi', stateId: 'kebbi' },
      { id: 'bunza', name: 'Bunza', stateId: 'kebbi' },
      { id: 'dandi', name: 'Dandi', stateId: 'kebbi' },
      { id: 'fakai', name: 'Fakai', stateId: 'kebbi' },
      { id: 'gwandu', name: 'Gwandu', stateId: 'kebbi' },
      { id: 'jega', name: 'Jega', stateId: 'kebbi' },
      { id: 'kalgo', name: 'Kalgo', stateId: 'kebbi' },
      { id: 'koko-besse', name: 'Koko/Besse', stateId: 'kebbi' },
      { id: 'maiyama', name: 'Maiyama', stateId: 'kebbi' },
      { id: 'ngaski', name: 'Ngaski', stateId: 'kebbi' },
      { id: 'sakaba', name: 'Sakaba', stateId: 'kebbi' },
      { id: 'shanga', name: 'Shanga', stateId: 'kebbi' },
      { id: 'suru', name: 'Suru', stateId: 'kebbi' },
      { id: 'wasagu-danko', name: 'Wasagu/Danko', stateId: 'kebbi' },
      { id: 'yauri', name: 'Yauri', stateId: 'kebbi' },
      { id: 'zuru', name: 'Zuru', stateId: 'kebbi' },
    ],
  },
  {
    id: 'kano',
    code: 'KN',
    name: 'Kano State',
    areas: [
      { id: 'ajingi', name: 'Ajingi', stateId: 'kano' },
      { id: 'albasu', name: 'Albasu', stateId: 'kano' },
      { id: 'bagwai', name: 'Bagwai', stateId: 'kano' },
      { id: 'bebeji', name: 'Bebeji', stateId: 'kano' },
      { id: 'bichi', name: 'Bichi', stateId: 'kano' },
      { id: 'bunkure', name: 'Bunkure', stateId: 'kano' },
      { id: 'dawakin-kudu', name: 'Dawakin Kudu', stateId: 'kano' },
      { id: 'dala', name: 'Dala', stateId: 'kano' },
      { id: 'dambatta', name: 'Dambatta', stateId: 'kano' },
      { id: 'doguwa', name: 'Doguwa', stateId: 'kano' },
      { id: 'dawakin-tofa', name: 'Dawakin Tofa', stateId: 'kano' },
      { id: 'fagge', name: 'Fagge', stateId: 'kano' },
      { id: 'gabasawa', name: 'Gabasawa', stateId: 'kano' },
      { id: 'gezawa', name: 'Gezawa', stateId: 'kano' },
      { id: 'garko', name: 'Garko', stateId: 'kano' },
      { id: 'gwale', name: 'Gwale', stateId: 'kano' },
      { id: 'garum-mallam', name: 'Garum Mallam', stateId: 'kano' },
      { id: 'gwarzo', name: 'Gwarzo', stateId: 'kano' },
      { id: 'gaya', name: 'Gaya', stateId: 'kano' },
      { id: 'kabo', name: 'Kabo', stateId: 'kano' },
      { id: 'kibiya', name: 'Kibiya', stateId: 'kano' },
      { id: 'kano-municipal', name: 'Kano Municipal', stateId: 'kano' },
      { id: 'kunchi', name: 'Kunchi', stateId: 'kano' },
      { id: 'kiru', name: 'Kiru', stateId: 'kano' },
      { id: 'kumbotso', name: 'Kumbotso', stateId: 'kano' },
      { id: 'kura', name: 'Kura', stateId: 'kano' },
      { id: 'karaye', name: 'Karaye', stateId: 'kano' },
      { id: 'madobi', name: 'Madobi', stateId: 'kano' },
      { id: 'minjibir', name: 'Minjibir', stateId: 'kano' },
      { id: 'makoda', name: 'Makoda', stateId: 'kano' },
      { id: 'nassarawa', name: 'Nassarawa', stateId: 'kano' },
      { id: 'rano', name: 'Rano', stateId: 'kano' },
      { id: 'rimin-gado', name: 'Rimin Gado', stateId: 'kano' },
      { id: 'rogo', name: 'Rogo', stateId: 'kano' },
      { id: 'shanono', name: 'Shanono', stateId: 'kano' },
      { id: 'sumaila', name: 'Sumaila', stateId: 'kano' },
      { id: 'takai', name: 'Takai', stateId: 'kano' },
      { id: 'tofa', name: 'Tofa', stateId: 'kano' },
      { id: 'tarauni', name: 'Tarauni', stateId: 'kano' },
      { id: 'tsanyawa', name: 'Tsanyawa', stateId: 'kano' },
      { id: 'tudun-wada', name: 'Tudun Wada', stateId: 'kano' },
      { id: 'ungogo', name: 'Ungogo', stateId: 'kano' },
      { id: 'warawa', name: 'Warawa', stateId: 'kano' },
      { id: 'wudil', name: 'Wudil', stateId: 'kano' },
    ],
  },
  {
    id: 'kogi',
    code: 'KO',
    name: 'Kogi State',
    areas: [
      { id: 'adavi', name: 'Adavi', stateId: 'kogi' },
      { id: 'ajaokuta', name: 'Ajaokuta', stateId: 'kogi' },
      { id: 'ankpa', name: 'Ankpa', stateId: 'kogi' },
      { id: 'bassa', name: 'Bassa', stateId: 'kogi' },
      { id: 'dekina', name: 'Dekina', stateId: 'kogi' },
      { id: 'ibaji', name: 'Ibaji', stateId: 'kogi' },
      { id: 'idah', name: 'Idah', stateId: 'kogi' },
      { id: 'ijumu', name: 'Ijumu', stateId: 'kogi' },
      { id: 'igalamela-odolu', name: 'Igalamela-Odolu', stateId: 'kogi' },
      { id: 'kabba-bunu', name: 'Kabba/Bunu', stateId: 'kogi' },
      { id: 'kogi', name: 'Kogi', stateId: 'kogi' },
      { id: 'lokoja', name: 'Lokoja', stateId: 'kogi' },
      { id: 'mopa-muro', name: 'Mopa-Muro', stateId: 'kogi' },
      { id: 'olamabolo', name: 'Olamabolo', stateId: 'kogi' },
      { id: 'ofu', name: 'Ofu', stateId: 'kogi' },
      { id: 'okehi', name: 'Okehi', stateId: 'kogi' },
      { id: 'omala', name: 'Omala', stateId: 'kogi' },
      { id: 'ogori-magongo', name: 'Ogori/Magongo', stateId: 'kogi' },
      { id: 'okene', name: 'Okene', stateId: 'kogi' },
      { id: 'yagba-east', name: 'Yagba East', stateId: 'kogi' },
      { id: 'yagba-west', name: 'Yagba West', stateId: 'kogi' },
    ],
  },
  {
    id: 'katsina',
    code: 'KT',
    name: 'Katsina State',
    areas: [
      { id: 'batagarawa', name: 'Batagarawa', stateId: 'katsina' },
      { id: 'bindawa', name: 'Bindawa', stateId: 'katsina' },
      { id: 'bakori', name: 'Bakori', stateId: 'katsina' },
      { id: 'batsari', name: 'Batsari', stateId: 'katsina' },
      { id: 'baure', name: 'Baure', stateId: 'katsina' },
      { id: 'charanchi', name: 'Charanchi', stateId: 'katsina' },
      { id: 'dandume', name: 'Dandume', stateId: 'katsina' },
      { id: 'danja', name: 'Danja', stateId: 'katsina' },
      { id: 'dan-musa', name: 'Dan Musa', stateId: 'katsina' },
      { id: 'daura', name: 'Daura', stateId: 'katsina' },
      { id: 'dutsin-ma', name: 'Dutsin-Ma', stateId: 'katsina' },
      { id: 'dutsi', name: 'Dutsi', stateId: 'katsina' },
      { id: 'faskari', name: 'Faskari', stateId: 'katsina' },
      { id: 'funtua', name: 'Funtua', stateId: 'katsina' },
      { id: 'ingawa', name: 'Ingawa', stateId: 'katsina' },
      { id: 'jibia', name: 'Jibia', stateId: 'katsina' },
      { id: 'katsina', name: 'Katsina', stateId: 'katsina' },
      { id: 'kusada', name: 'Kusada', stateId: 'katsina' },
      { id: 'kafur', name: 'Kafur', stateId: 'katsina' },
      { id: 'kankia', name: 'Kankia', stateId: 'katsina' },
      { id: 'kankara', name: 'Kankara', stateId: 'katsina' },
      { id: 'kurfi', name: 'Kurfi', stateId: 'katsina' },
      { id: 'kaita', name: 'Kaita', stateId: 'katsina' },
      { id: 'mai-adua', name: 'Mai\'adua', stateId: 'katsina' },
      { id: 'malumfashi', name: 'Malumfashi', stateId: 'katsina' },
      { id: 'mani', name: 'Mani', stateId: 'katsina' },
      { id: 'mashi', name: 'Mashi', stateId: 'katsina' },
      { id: 'musawa', name: 'Musawa', stateId: 'katsina' },
      { id: 'matazu', name: 'Matazu', stateId: 'katsina' },
      { id: 'rimi', name: 'Rimi', stateId: 'katsina' },
      { id: 'sabuwa', name: 'Sabuwa', stateId: 'katsina' },
      { id: 'safana', name: 'Safana', stateId: 'katsina' },
      { id: 'sandamu', name: 'Sandamu', stateId: 'katsina' },
      { id: 'zango', name: 'Zango', stateId: 'katsina' },
    ],
  },
  {
    id: 'kwara',
    code: 'KW',
    name: 'Kwara State',
    areas: [
      { id: 'asa', name: 'Asa', stateId: 'kwara' },
      { id: 'baruten', name: 'Baruten', stateId: 'kwara' },
      { id: 'edu', name: 'Edu', stateId: 'kwara' },
      { id: 'ekiti', name: 'Ekiti', stateId: 'kwara' },
      { id: 'ilorin-east', name: 'Ilorin East', stateId: 'kwara' },
      { id: 'ifelodun', name: 'Ifelodun', stateId: 'kwara' },
      { id: 'isin', name: 'Isin', stateId: 'kwara' },
      { id: 'irepodun', name: 'Irepodun', stateId: 'kwara' },
      { id: 'ilorin-south', name: 'Ilorin South', stateId: 'kwara' },
      { id: 'ilorin-west', name: 'Ilorin West', stateId: 'kwara' },
      { id: 'kaiama', name: 'Kaiama', stateId: 'kwara' },
      { id: 'moro', name: 'Moro', stateId: 'kwara' },
      { id: 'offa', name: 'Offa', stateId: 'kwara' },
      { id: 'oke-ero', name: 'Oke-Ero', stateId: 'kwara' },
      { id: 'oyun', name: 'Oyun', stateId: 'kwara' },
      { id: 'pategi', name: 'Pategi', stateId: 'kwara' },
    ],
  },
  {
    id: 'lagos',
    code: 'LA',
    name: 'Lagos State',
    areas: [
      { id: 'agege', name: 'Agege', stateId: 'lagos' },
      { id: 'ajeromi-ifelodun', name: 'Ajeromi-Ifelodun', stateId: 'lagos' },
      { id: 'alimosho', name: 'Alimosho', stateId: 'lagos' },
      { id: 'amuwo-odofin', name: 'Amuwo-Odofin', stateId: 'lagos' },
      { id: 'apapa', name: 'Apapa', stateId: 'lagos' },
      { id: 'badagry', name: 'Badagry', stateId: 'lagos' },
      { id: 'eti-osa', name: 'Eti-Osa', stateId: 'lagos' },
      { id: 'epe', name: 'Epe', stateId: 'lagos' },
      { id: 'ikorodu', name: 'Ikorodu', stateId: 'lagos' },
      { id: 'ifako-ijaye', name: 'Ifako-Ijaye', stateId: 'lagos' },
      { id: 'ikeja', name: 'Ikeja', stateId: 'lagos' },
      { id: 'ibeju-lekki', name: 'Ibeju/Lekki', stateId: 'lagos' },
      { id: 'kosofe', name: 'Kosofe', stateId: 'lagos' },
      { id: 'lagos-island', name: 'Lagos Island', stateId: 'lagos' },
      { id: 'lagos-mainland', name: 'Lagos Mainland', stateId: 'lagos' },
      { id: 'mushin', name: 'Mushin', stateId: 'lagos' },
      { id: 'oshodi-isolo', name: 'Oshodi-Isolo', stateId: 'lagos' },
      { id: 'ojo', name: 'Ojo', stateId: 'lagos' },
      { id: 'shomolu', name: 'Shomolu', stateId: 'lagos' },
      { id: 'surulere', name: 'Surulere', stateId: 'lagos' },
    ],
  },
  {
    id: 'nasarawa',
    code: 'NA',
    name: 'Nasarawa State',
    areas: [
      { id: 'akwanga', name: 'Akwanga', stateId: 'nasarawa' },
      { id: 'awe', name: 'Awe', stateId: 'nasarawa' },
      { id: 'doma', name: 'Doma', stateId: 'nasarawa' },
      { id: 'karu', name: 'Karu', stateId: 'nasarawa' },
      { id: 'keffi', name: 'Keffi', stateId: 'nasarawa' },
      { id: 'keana', name: 'Keana', stateId: 'nasarawa' },
      { id: 'kokona', name: 'Kokona', stateId: 'nasarawa' },
      { id: 'lafia', name: 'Lafia', stateId: 'nasarawa' },
      { id: 'nassarawa', name: 'Nassarawa', stateId: 'nasarawa' },
      { id: 'nassarawa-egon', name: 'Nassarawa Egon', stateId: 'nasarawa' },
      { id: 'obi', name: 'Obi', stateId: 'nasarawa' },
      { id: 'toto', name: 'Toto', stateId: 'nasarawa' },
      { id: 'wamba', name: 'Wamba', stateId: 'nasarawa' },
    ],
  },
  {
    id: 'niger',
    code: 'NI',
    name: 'Niger State',
    areas: [
      { id: 'agaie', name: 'Agaie', stateId: 'niger' },
      { id: 'agwara', name: 'Agwara', stateId: 'niger' },
      { id: 'bida', name: 'Bida', stateId: 'niger' },
      { id: 'borgu', name: 'Borgu', stateId: 'niger' },
      { id: 'bosso', name: 'Bosso', stateId: 'niger' },
      { id: 'chanchaga', name: 'Chanchaga', stateId: 'niger' },
      { id: 'edati', name: 'Edati', stateId: 'niger' },
      { id: 'gbako', name: 'Gbako', stateId: 'niger' },
      { id: 'gurara', name: 'Gurara', stateId: 'niger' },
      { id: 'katcha', name: 'Katcha', stateId: 'niger' },
      { id: 'kontagora', name: 'Kontagora', stateId: 'niger' },
      { id: 'lapai', name: 'Lapai', stateId: 'niger' },
      { id: 'lavun', name: 'Lavun', stateId: 'niger' },
      { id: 'magama', name: 'Magama', stateId: 'niger' },
      { id: 'mokwa', name: 'Mokwa', stateId: 'niger' },
      { id: 'mariga', name: 'Mariga', stateId: 'niger' },
      { id: 'mashegu', name: 'Mashegu', stateId: 'niger' },
      { id: 'muya', name: 'Muya', stateId: 'niger' },
      { id: 'paikoro', name: 'Paikoro', stateId: 'niger' },
      { id: 'rafi', name: 'Rafi', stateId: 'niger' },
      { id: 'rijau', name: 'Rijau', stateId: 'niger' },
      { id: 'shiroro', name: 'Shiroro', stateId: 'niger' },
      { id: 'suleja', name: 'Suleja', stateId: 'niger' },
      { id: 'tafa', name: 'Tafa', stateId: 'niger' },
      { id: 'wushishi', name: 'Wushishi', stateId: 'niger' },
    ],
  },
  {
    id: 'ogun',
    code: 'OG',
    name: 'Ogun State',
    areas: [
      { id: 'abeokuta-north', name: 'Abeokuta North', stateId: 'ogun' },
      { id: 'ado-odo-ota', name: 'Ado-Odo/Ota', stateId: 'ogun' },
      { id: 'abeokuta-south', name: 'Abeokuta South', stateId: 'ogun' },
      { id: 'egbado-north', name: 'Egbado North', stateId: 'ogun' },
      { id: 'egbado-south', name: 'Egbado South', stateId: 'ogun' },
      { id: 'ewekoro', name: 'Ewekoro', stateId: 'ogun' },
      { id: 'imeko-afon', name: 'Imeko-Afon', stateId: 'ogun' },
      { id: 'ijebu-east', name: 'Ijebu East', stateId: 'ogun' },
      { id: 'ifo', name: 'Ifo', stateId: 'ogun' },
      { id: 'ijebu-north', name: 'Ijebu North', stateId: 'ogun' },
      { id: 'ikenne', name: 'Ikenne', stateId: 'ogun' },
      { id: 'ijebu-north-east', name: 'Ijebu North East', stateId: 'ogun' },
      { id: 'ijebu-ode', name: 'Ijebu Ode', stateId: 'ogun' },
      { id: 'ipokia', name: 'Ipokia', stateId: 'ogun' },
      { id: 'odogbolu', name: 'Odogbolu', stateId: 'ogun' },
      { id: 'odeda', name: 'Odeda', stateId: 'ogun' },
      { id: 'obafemi-owode', name: 'Obafemi-Owode', stateId: 'ogun' },
      { id: 'ogun-waterside', name: 'Ogun Waterside', stateId: 'ogun' },
      { id: 'remo-north', name: 'Remo North', stateId: 'ogun' },
      { id: 'shagamu', name: 'Shagamu', stateId: 'ogun' },
    ],
  },
  {
    id: 'ondo',
    code: 'ON',
    name: 'Ondo State',
    areas: [
      { id: 'akoko-south-east', name: 'Akoko South East', stateId: 'ondo' },
      { id: 'akure-north', name: 'Akure North', stateId: 'ondo' },
      { id: 'akoko-north-east', name: 'Akoko North East', stateId: 'ondo' },
      { id: 'akure-south', name: 'Akure South', stateId: 'ondo' },
      { id: 'akoko-south-west', name: 'Akoko South West', stateId: 'ondo' },
      { id: 'akoko-north-west', name: 'Akoko North West', stateId: 'ondo' },
      { id: 'ese-odo', name: 'Ese-Odo', stateId: 'ondo' },
      { id: 'idanre', name: 'Idanre', stateId: 'ondo' },
      { id: 'ifedore', name: 'Ifedore', stateId: 'ondo' },
      { id: 'ilaje', name: 'Ilaje', stateId: 'ondo' },
      { id: 'ile-oluji-okeigbo', name: 'Ile-Oluji-Okeigbo', stateId: 'ondo' },
      { id: 'irele', name: 'Irele', stateId: 'ondo' },
      { id: 'odigbo', name: 'Odigbo', stateId: 'ondo' },
      { id: 'ondo-east', name: 'Ondo East', stateId: 'ondo' },
      { id: 'okitipupa', name: 'Okitipupa', stateId: 'ondo' },
      { id: 'owo', name: 'Owo', stateId: 'ondo' },
      { id: 'ose', name: 'Ose', stateId: 'ondo' },
      { id: 'ondo-west', name: 'Ondo West', stateId: 'ondo' },
    ],
  },
  {
    id: 'osun',
    code: 'OS',
    name: 'Osun State',
    areas: [
      { id: 'aiyedade', name: 'Aiyedade', stateId: 'osun' },
      { id: 'atakunmosa-east', name: 'Atakunmosa East', stateId: 'osun' },
      { id: 'aiyedire', name: 'Aiyedire', stateId: 'osun' },
      { id: 'atakunmosa-west', name: 'Atakunmosa West', stateId: 'osun' },
      { id: 'boluwaduro', name: 'Boluwaduro', stateId: 'osun' },
      { id: 'boripe', name: 'Boripe', stateId: 'osun' },
      { id: 'egbedore', name: 'Egbedore', stateId: 'osun' },
      { id: 'ejigbo', name: 'Ejigbo', stateId: 'osun' },
      { id: 'ede-north', name: 'Ede North', stateId: 'osun' },
      { id: 'ede-south', name: 'Ede South', stateId: 'osun' },
      { id: 'ife-central', name: 'Ife Central', stateId: 'osun' },
      { id: 'ifelodun', name: 'Ifelodun', stateId: 'osun' },
      { id: 'ife-east', name: 'Ife East', stateId: 'osun' },
      { id: 'ifedayo', name: 'Ifedayo', stateId: 'osun' },
      { id: 'ilesha-east', name: 'Ilesha East', stateId: 'osun' },
      { id: 'isokan', name: 'Isokan', stateId: 'osun' },
      { id: 'ila', name: 'Ila', stateId: 'osun' },
      { id: 'ife-north', name: 'Ife North', stateId: 'osun' },
      { id: 'iwo', name: 'Iwo', stateId: 'osun' },
      { id: 'irepodun', name: 'Irepodun', stateId: 'osun' },
      { id: 'irewole', name: 'Irewole', stateId: 'osun' },
      { id: 'ife-south', name: 'Ife South', stateId: 'osun' },
      { id: 'ilesha-west', name: 'Ilesha West', stateId: 'osun' },
      { id: 'obokun', name: 'Obokun', stateId: 'osun' },
      { id: 'oriade', name: 'Oriade', stateId: 'osun' },
      { id: 'ola-oluwa', name: 'Ola-Oluwa', stateId: 'osun' },
      { id: 'olorunda', name: 'Olorunda', stateId: 'osun' },
      { id: 'odo-otin', name: 'Odo-Otin', stateId: 'osun' },
      { id: 'orolu', name: 'Orolu', stateId: 'osun' },
      { id: 'osogbo', name: 'Osogbo', stateId: 'osun' },
    ],
  },
  {
    id: 'oyo',
    code: 'OY',
    name: 'Oyo State',
    areas: [
      { id: 'afijio', name: 'Afijio', stateId: 'oyo' },
      { id: 'akinyele', name: 'Akinyele', stateId: 'oyo' },
      { id: 'atisbo', name: 'Atisbo', stateId: 'oyo' },
      { id: 'atiba', name: 'Atiba', stateId: 'oyo' },
      { id: 'egbeda', name: 'Egbeda', stateId: 'oyo' },
      { id: 'ibarapa-east', name: 'Ibarapa East', stateId: 'oyo' },
      { id: 'ibadan-north', name: 'Ibadan North', stateId: 'oyo' },
      { id: 'ibarapa-central', name: 'Ibarapa Central', stateId: 'oyo' },
      { id: 'ido', name: 'Ido', stateId: 'oyo' },
      { id: 'ibadan-south-east', name: 'Ibadan South East', stateId: 'oyo' },
      { id: 'iwajowa', name: 'Iwajowa', stateId: 'oyo' },
      { id: 'ibadan-north-east', name: 'Ibadan North East', stateId: 'oyo' },
      { id: 'ibarapa-north', name: 'Ibarapa North', stateId: 'oyo' },
      { id: 'irepo', name: 'Irepo', stateId: 'oyo' },
      { id: 'ibadan-south-west', name: 'Ibadan South West', stateId: 'oyo' },
      { id: 'itesiwaju', name: 'Itesiwaju', stateId: 'oyo' },
      { id: 'ibadan-north-west', name: 'Ibadan North West', stateId: 'oyo' },
      { id: 'iseyin', name: 'Iseyin', stateId: 'oyo' },
      { id: 'kajola', name: 'Kajola', stateId: 'oyo' },
      { id: 'lagelu', name: 'Lagelu', stateId: 'oyo' },
      { id: 'ona-ara', name: 'Ona-Ara', stateId: 'oyo' },
      { id: 'oyo-east', name: 'Oyo East', stateId: 'oyo' },
      { id: 'ori-ire', name: 'Ori Ire', stateId: 'oyo' },
      { id: 'olorunsogo', name: 'Olorunsogo', stateId: 'oyo' },
      { id: 'ogbomosho-north', name: 'Ogbomosho North', stateId: 'oyo' },
      { id: 'ogo-oluwa', name: 'Ogo Oluwa', stateId: 'oyo' },
      { id: 'orelope', name: 'Orelope', stateId: 'oyo' },
      { id: 'ogbmosho-south', name: 'Ogbmosho South', stateId: 'oyo' },
      { id: 'oyo-west', name: 'Oyo West', stateId: 'oyo' },
      { id: 'oluyole', name: 'Oluyole', stateId: 'oyo' },
      { id: 'saki-east', name: 'Saki East', stateId: 'oyo' },
      { id: 'surulere', name: 'Surulere', stateId: 'oyo' },
      { id: 'saki-west', name: 'Saki West', stateId: 'oyo' },
    ],
  },
  {
    id: 'plateau',
    code: 'PL',
    name: 'Plateau State',
    areas: [
      { id: 'bassa', name: 'Bassa', stateId: 'plateau' },
      { id: 'barkin-ladi', name: 'Barkin Ladi', stateId: 'plateau' },
      { id: 'bokkos', name: 'Bokkos', stateId: 'plateau' },
      { id: 'jos-east', name: 'Jos East', stateId: 'plateau' },
      { id: 'jos-north', name: 'Jos North', stateId: 'plateau' },
      { id: 'jos-south', name: 'Jos South', stateId: 'plateau' },
      { id: 'kanke', name: 'Kanke', stateId: 'plateau' },
      { id: 'kanam', name: 'Kanam', stateId: 'plateau' },
      { id: 'langtang-north', name: 'Langtang North', stateId: 'plateau' },
      { id: 'langtang-south', name: 'Langtang South', stateId: 'plateau' },
      { id: 'mangu', name: 'Mangu', stateId: 'plateau' },
      { id: 'mikang', name: 'Mikang', stateId: 'plateau' },
      { id: 'pankshin', name: 'Pankshin', stateId: 'plateau' },
      { id: 'qua-an-pan', name: 'Qua\'an Pan', stateId: 'plateau' },
      { id: 'riyom', name: 'Riyom', stateId: 'plateau' },
      { id: 'shendam', name: 'Shendam', stateId: 'plateau' },
      { id: 'wase', name: 'Wase', stateId: 'plateau' },
    ],
  },
  {
    id: 'rivers',
    code: 'RI',
    name: 'Rivers State',
    areas: [
      { id: 'ahoada-east', name: 'Ahoada East', stateId: 'rivers' },
      { id: 'andoni', name: 'Andoni', stateId: 'rivers' },
      { id: 'abua-odual', name: 'Abua/Odual', stateId: 'rivers' },
      { id: 'asari-toru', name: 'Asari-Toru', stateId: 'rivers' },
      { id: 'akuku-toru', name: 'Akuku Toru', stateId: 'rivers' },
      { id: 'ahoada-west', name: 'Ahoada West', stateId: 'rivers' },
      { id: 'bonny', name: 'Bonny', stateId: 'rivers' },
      { id: 'degema', name: 'Degema', stateId: 'rivers' },
      { id: 'eleme', name: 'Eleme', stateId: 'rivers' },
      { id: 'emuoha', name: 'Emuoha', stateId: 'rivers' },
      { id: 'etche', name: 'Etche', stateId: 'rivers' },
      { id: 'gokana', name: 'Gokana', stateId: 'rivers' },
      { id: 'ikwerre', name: 'Ikwerre', stateId: 'rivers' },
      { id: 'khana', name: 'Khana', stateId: 'rivers' },
      { id: 'obio-akpor', name: 'Obio/Akpor', stateId: 'rivers' },
      { id: 'ogu-bolo', name: 'Ogu/Bolo', stateId: 'rivers' },
      { id: 'ogba-egbema-ndoni', name: 'Ogba/Egbema/Ndoni', stateId: 'rivers' },
      { id: 'okrika', name: 'Okrika', stateId: 'rivers' },
      { id: 'omumma', name: 'Omumma', stateId: 'rivers' },
      { id: 'opobo-nkoro', name: 'Opobo/Nkoro', stateId: 'rivers' },
      { id: 'oyigbo', name: 'Oyigbo', stateId: 'rivers' },
      { id: 'port-harcourt', name: 'Port-Harcourt', stateId: 'rivers' },
      { id: 'tai', name: 'Tai', stateId: 'rivers' },
    ],
  },
  {
    id: 'sokoto',
    code: 'SO',
    name: 'Sokoto State',
    areas: [
      { id: 'binji', name: 'Binji', stateId: 'sokoto' },
      { id: 'bodinga', name: 'Bodinga', stateId: 'sokoto' },
      { id: 'dange-shuni', name: 'Dange-Shuni', stateId: 'sokoto' },
      { id: 'gada', name: 'Gada', stateId: 'sokoto' },
      { id: 'goronyo', name: 'Goronyo', stateId: 'sokoto' },
      { id: 'gudu', name: 'Gudu', stateId: 'sokoto' },
      { id: 'gwadabawa', name: 'Gwadabawa', stateId: 'sokoto' },
      { id: 'illela', name: 'Illela', stateId: 'sokoto' },
      { id: 'isa', name: 'Isa', stateId: 'sokoto' },
      { id: 'kebbe', name: 'Kebbe', stateId: 'sokoto' },
      { id: 'kware', name: 'Kware', stateId: 'sokoto' },
      { id: 'rabah', name: 'Rabah', stateId: 'sokoto' },
      { id: 'sabon-birni', name: 'Sabon Birni', stateId: 'sokoto' },
      { id: 'shagari', name: 'Shagari', stateId: 'sokoto' },
      { id: 'silame', name: 'Silame', stateId: 'sokoto' },
      { id: 'sokoto-north', name: 'Sokoto North', stateId: 'sokoto' },
      { id: 'sokoto-south', name: 'Sokoto South', stateId: 'sokoto' },
      { id: 'tureta', name: 'Tureta', stateId: 'sokoto' },
      { id: 'tambuwal', name: 'Tambuwal', stateId: 'sokoto' },
      { id: 'tangaza', name: 'Tangaza', stateId: 'sokoto' },
      { id: 'wamako', name: 'Wamako', stateId: 'sokoto' },
      { id: 'wurno', name: 'Wurno', stateId: 'sokoto' },
      { id: 'yabo', name: 'Yabo', stateId: 'sokoto' },
    ],
  },
  {
    id: 'taraba',
    code: 'TA',
    name: 'Taraba State',
    areas: [
      { id: 'ardo-kola', name: 'Ardo-Kola', stateId: 'taraba' },
      { id: 'bali', name: 'Bali', stateId: 'taraba' },
      { id: 'donga', name: 'Donga', stateId: 'taraba' },
      { id: 'gashaka', name: 'Gashaka', stateId: 'taraba' },
      { id: 'gassol', name: 'Gassol', stateId: 'taraba' },
      { id: 'ibi', name: 'Ibi', stateId: 'taraba' },
      { id: 'jalingo', name: 'Jalingo', stateId: 'taraba' },
      { id: 'karim-lamido', name: 'Karim-Lamido', stateId: 'taraba' },
      { id: 'kurmi', name: 'Kurmi', stateId: 'taraba' },
      { id: 'lau', name: 'Lau', stateId: 'taraba' },
      { id: 'sardauna', name: 'Sardauna', stateId: 'taraba' },
    ],
  },
];

// Helper function to get all states
export const getAllStates = () => {
  return STATES.map(state => ({
    id: state.id,
    code: state.code,
    name: state.name,
  }));
};

// Helper function to get all areas for a state
export const getAreasByStateId = (stateId: string) => {
  const state = STATES.find(s => s.id === stateId);
  return state?.areas || [];
};

// Helper function to get state by code
export const getStateByCode = (code: string) => {
  return STATES.find(state => state.code === code.toUpperCase());
};

// Helper function to get area by id
export const getAreaById = (areaId: string) => {
  for (const state of STATES) {
    const area = state.areas.find(a => a.id === areaId);
    if (area) return { ...area, stateName: state.name, stateCode: state.code };
  }
  return null;
}; 